services:
  db:
    image: mysql:8.0
    container_name: mysql_inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda_virtual
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: tienda_virtual
      JWT_SECRET: clave_secreta_para_desarrollo_123
    depends_on:
      - db

volumes:
  mysql_data:
